version: "3"
services:
  redis:
    image: redis
    restart: always
  postgres:
    image: postgres
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: outline
    restart: always
  s3:
    image: fake-s3:v001
    build:
      context: .
      dockerfile: Dockerfile.fake-s3
    restart: always
    volumes:
      - ./fakes3:/fakes3_root
  outline:
    image: outline:v001
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - .:/opt/outline
    restart: always
    depends_on:
      - postgres
      - redis
      - s3
